### ISSUE TITLE
#logoと#worksがうまく縦に並ばない問題について

### ISSUE THREAD

**Issue by tac0810** [ezm-k/Portfolio#1]
- クラスがあっていません
https://github.com/ezm-k/Portfolio/blob/dd0eebf0326c6684c0f245764bffaf1b569e372d/index.html#L41

```html
<div id="logo" class="logo">
```

- height 100%だとちょっと微妙なので以下のようにした方がいいかもです。
- ついでにセンター揃えのコードもこう書くと今風な気がします
https://github.com/ezm-k/Portfolio/blob/dd0eebf0326c6684c0f245764bffaf1b569e372d/css/styles.css#L158-L162

```css
.logo {
  width: 100%;

  /* %からvhへ */
  height: 100vh;
  position: relative;

  /* 追加 */
  display: flex;
  align-items: center;
  justify-content: center;
}

#logo h1 {
  text-align: center;

  /* 色々削除 */

  letter-spacing: 0.2em;
}
```
